### ISSUE TITLE
Allow the static ip address to be assigned even if there's no actual gateway

### ISSUE THREAD

**Issue by syangsao** [machacekondra/ovirt-ansible-example#1]
The current ovirt_host_networks requires a gateway to be specified when using the "static" option for the boot_protocol value.  For private networks that do not have a gateway, this should be allowed to pass.  RHV 4.1 does allow the creation of a network without the gateway being specified.

![ovirt-network](https://user-images.githubusercontent.com/11576324/28599394-d62c8bac-716f-11e7-85ec-08e0cf77145c.png)

**Comment by machacekondra** [comment]
@syangsao It works for me just fine:

```yaml
  - name: Assign test network to eth2
    ovirt_host_networks:
      auth: "{{ ovirt_auth }}"
      name: host1
      interface: eth2
      networks:
        - name: test2
          boot_protocol: static
          address: 1.2.3.5
          netmask: 255.255.255.0
          version: v4
      save: true
      check: true
```
